- name: Config tomcat environment
  template: 
   src:  "{{ tomcat_template_config_src}}"
   dest: "{{ tomcat_template_config_dest}}"
   owner: "{{ tomcat_template_config_owner}}"
   group: "{{ tomcat_template_config_group}}"
   mode: "{{ tomcat_template_config_mode}}"
  notify:
   - Restart Tomcat 
